import React, { useMemo, useState } from 'react';
import { outputs, claims, audienceInfo } from './data/mock';

const nav = [
  ['workspace','⌂','Workspace'], ['understanding','◫','Source Understanding'], ['outputs','✦','Outputs'],
  ['verification','✓','Verification'], ['audit','◉','Audit & Integrity']
];

function Logo(){return <div className="brand"><div className="brand-mark">TX</div><div><b>TRANSFORM-X</b><span>Trusted GenAI Transformation</span></div></div>}
function Badge({children,tone='blue'}){return <span className={`badge ${tone}`}>{children}</span>}
function Stat({value,label,accent}){return <div className="stat"><strong className={accent||''}>{value}</strong><span>{label}</span></div>}

function Workspace({onTransform}){
  const [audience,setAudience]=useState('Executive');
  const [objective,setObjective]=useState('Decision Making');
  const [tone,setTone]=useState('Professional');
  const [detail,setDetail]=useState('Medium');
  const [source,setSource]=useState('');
  const [files,setFiles]=useState([]);
  const [selected,setSelected]=useState(['summary','advisory','linkedin','presentation']);
  const toggle=(id)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
  const handleFiles=(e)=>setFiles(Array.from(e.target.files||[]));
  return <>
    <Header title="Transformation Workspace" subtitle="Turn one trusted source into audience-ready, verified communication." />
    <div className="workspace-grid">
      <section className="panel source-panel">
        <div className="panel-head"><div><h2>1. Source Ingestion</h2><p>Upload a document or paste trusted source content.</p></div><Badge>SECURE INPUT</Badge></div>
        <div className="dropzone">
          <div className="upload-icon">↑</div><h3>Drop files here</h3><p>PDF, DOCX or TXT · Max 20 MB</p>
          <label className="btn secondary">Choose files<input hidden type="file" multiple accept=".pdf,.docx,.txt" onChange={handleFiles}/></label>
          {files.length>0 && <div className="file-list">{files.map(f=><div key={f.name}>▤ {f.name}<span>{Math.round(f.size/1024)} KB</span></div>)}</div>}
        </div>
        <div className="or"><span>OR PASTE SOURCE</span></div>
        <textarea value={source} onChange={e=>setSource(e.target.value)} placeholder="Paste an advisory, incident report, article, policy document or other trusted source..." />
      </section>
      <section className="panel config-panel">
        <div className="panel-head"><div><h2>2. Transformation Control</h2><p>Audience changes what information gets prioritized.</p></div><span className="live-dot">● Live</span></div>
        <Field label="Target Audience"><select value={audience} onChange={e=>setAudience(e.target.value)}>{Object.keys(audienceInfo).map(x=><option key={x}>{x}</option>)}</select></Field>
        <Field label="Communication Objective"><select value={objective} onChange={e=>setObjective(e.target.value)}><option>Decision Making</option><option>Awareness</option><option>Incident Response</option><option>Public Notification</option><option>Training</option></select></Field>
        <div className="two-fields"><Field label="Tone"><select value={tone} onChange={e=>setTone(e.target.value)}><option>Professional</option><option>Formal</option><option>Technical</option><option>Neutral</option><option>Urgent</option></select></Field><Field label="Detail"><select value={detail} onChange={e=>setDetail(e.target.value)}><option>Brief</option><option>Medium</option><option>Detailed</option><option>Highly Technical</option></select></Field></div>
        <div className="audience-preview"><div className="mini-title">AUDIENCE INTELLIGENCE</div><p>{audienceInfo[audience].description}</p><div className="priority-bars">{audienceInfo[audience].priorities.map(([name,val])=><div key={name}><span>{name}</span><div className="bar"><i style={{width:`${val}%`}} /></div></div>)}</div></div>
      </section>
    </div>
    <section className="panel output-selector">
      <div className="panel-head"><div><h2>3. Select Outputs</h2><p>Format-specific schemas are applied before generation.</p></div><span>{selected.length} selected</span></div>
      <div className="output-options">{outputs.map(o=><button className={`output-option ${selected.includes(o.id)?'selected':''}`} key={o.id} onClick={()=>toggle(o.id)}><span className="option-icon">{o.icon}</span><span><b>{o.title}</b><small>{o.type}</small></span><span className="check">{selected.includes(o.id)?'✓':'+'}</span></button>)}</div>
      <div className="transform-row"><div><strong>Source-grounded generation</strong><span>Facts → Audience priorities → Output schema → RAG + LLM → Verification</span></div><button className="btn primary" onClick={()=>onTransform({audience,objective,tone,detail,selected,source,files})}>TRANSFORM-X <span>→</span></button></div>
    </section>
  </>
}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Header({title,subtitle}){return <div className="page-header"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="header-actions"><button className="icon-btn">⌕</button><div className="user">MY</div></div></div>}

function Understanding(){return <><Header title="Source Understanding" subtitle="Structured information extracted before any content is generated."/><div className="stats"><Stat value="1" label="Source"/><Stat value="42" label="Facts extracted"/><Stat value="8" label="Entities"/><Stat value="6" label="Risks & findings"/><Stat value="11" label="Actions"/></div><div className="under-grid"><section className="panel"><div className="panel-head"><div><h2>Structured Information Layer</h2><p>Evidence-aware representation of the source.</p></div><Badge tone="green">READY</Badge></div><div className="info-cards">{[['Facts','42','Key factual statements extracted'],['Events','7','Timeline and incident events'],['Entities','8','People, systems, organizations'],['Risks','6','Risks and potential impact'],['Actions','11','Recommendations and actions'],['Evidence','37','Source-linked evidence chunks']].map(([a,b,c])=><div className="info-card" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div></section><section className="panel"><div className="panel-head"><div><h2>Evidence Preview</h2><p>Source snippets retained for grounding.</p></div></div><div className="evidence"><div><Badge tone="purple">PAGE 8 · ¶3</Badge><p>“The incident was detected on 12 August after unusual authentication activity was observed.”</p></div><div><Badge tone="purple">PAGE 9 · AFFECTED INFRASTRUCTURE</Badge><p>“Three internal servers were identified as affected during the investigation.”</p></div><div><Badge tone="orange">PAGE 13 · RECOMMENDATIONS</Badge><p>“Rotate exposed credentials and review privileged access controls.”</p></div></div></section></div></>}

function Outputs(){const [active,setActive]=useState(outputs[0]);return <><Header title="Generated Outputs" subtitle="Each artifact uses a format-specific schema and the same verified source."/><div className="output-layout"><div className="output-list">{outputs.map(o=><button key={o.id} onClick={()=>setActive(o)} className={`output-card ${active.id===o.id?'active':''}`}><div className="big-icon">{o.icon}</div><div><b>{o.title}</b><span>{o.description}</span></div><Badge tone={o.status==='Verified'?'green':'orange'}>{o.status}</Badge></button>)}</div><section className="panel preview-panel"><div className="preview-toolbar"><div><Badge tone="green">{active.score}% GROUNDED</Badge><h2>{active.title}</h2></div><div className="toolbar-buttons"><button className="btn secondary">Edit</button><button className="btn secondary">Verify</button><button className="btn secondary">Export</button></div></div><div className="document-preview"><h3>{active.title}</h3><p className="muted">Generated for Executive audience · Professional tone · Medium detail</p><hr/><h4>Situation</h4><p>The source reports a security incident involving internal infrastructure. The transformation prioritizes operational impact, risk and decisions required by leadership.</p><h4>Key Findings</h4><ul><li>Incident detected on 12 August.</li><li>Three internal servers were affected.</li><li>Credential exposure requires immediate review and rotation.</li></ul><h4>Recommended Actions</h4><ol><li>Rotate exposed credentials.</li><li>Review privileged access controls.</li><li>Monitor affected systems and preserve investigation evidence.</li></ol><div className="source-tag">✓ Claims are linked to source evidence</div></div></section></div></>}

function Verification(){const [items,setItems]=useState(claims);const counts=useMemo(()=>({supported:items.filter(x=>x.status==='supported').length,review:items.filter(x=>x.status==='review').length,unsupported:items.filter(x=>x.status==='unsupported').length}),[items]);const approve=(id)=>setItems(xs=>xs.map(x=>x.id===id?{...x,status:'supported'}:x));return <><Header title="Claim Verification" subtitle="Generated claims are checked against retrieved source evidence before approval."/><div className="verification-stats"><Stat value={items.length} label="Claims checked"/><Stat value={counts.supported} label="Supported" accent="green-text"/><Stat value={counts.review} label="Review required" accent="orange-text"/><Stat value={counts.unsupported} label="Unsupported" accent="red-text"/></div><section className="panel claims-panel"><div className="panel-head"><div><h2>Claim → Evidence Mapping</h2><p>Human reviewer remains in control of every decision.</p></div><Badge tone="green">SOURCE GROUNDED</Badge></div>{items.map(c=><div className="claim" key={c.id}><div className={`claim-status ${c.status}`}>{c.status==='supported'?'✓':c.status==='review'?'!':'×'}</div><div className="claim-main"><b>Claim {c.id}</b><p>“{c.text}”</p><span className="evidence-line">Evidence: {c.evidence}</span></div><div className="claim-actions"><Badge tone={c.status==='supported'?'green':c.status==='review'?'orange':'red'}>{c.status==='supported'?'SUPPORTED':c.status==='review'?'NEEDS REVIEW':'UNSUPPORTED'}</Badge>{c.status!=='supported'&&<button className="btn tiny" onClick={()=>approve(c.id)}>Approve</button>}<button className="text-btn">View Evidence</button></div></div>)}</section></>}

function Audit(){return <><Header title="Audit & Integrity" subtitle="Every generation, review and export creates a traceable activity record."/><div className="audit-grid"><section className="panel"><div className="panel-head"><div><h2>Audit Trail</h2><p>Immutable-style event history for the prototype.</p></div><Badge tone="purple">VERSION 04</Badge></div><div className="timeline">{[['09:41','Source uploaded','Incident_Report.pdf'],['09:42','Source understood','42 facts · 7 events · 37 evidence chunks'],['09:43','Outputs generated','4 artifacts created'],['09:44','Claims verified','34 supported · 2 review · 1 unsupported'],['09:46','Human review','Reviewer approved Executive Summary'],['09:47','Integrity record','SHA-256 hash generated']].map(([time,title,detail],i)=><div className="timeline-item" key={time}><div className="timeline-dot">{i+1}</div><div><small>{time}</small><b>{title}</b><span>{detail}</span></div></div>)}</div></section><section className="panel integrity"><div className="panel-head"><div><h2>Integrity Record</h2><p>Approved artifact fingerprint.</p></div><Badge tone="green">VERIFIED</Badge></div><div className="hash-box"><span>SHA-256</span><code>9b71d224bd62f3785d96d46ad3ea3d73c...</code><button className="btn secondary">Copy</button></div><div className="ledger"><div><span>Document ID</span><b>TX-2026-00421</b></div><div><span>Version</span><b>v4.0</b></div><div><span>Approval</span><b>Human Approved</b></div><div><span>Ledger</span><b>Permissioned Blockchain</b></div></div><div className="integrity-note">⛓ Hash can be recalculated later and compared with the recorded integrity value to detect unauthorized modification.</div></section></div></>}

function App(){const [page,setPage]=useState('workspace');const [toast,setToast]=useState('');const transform=(config)=>{setToast(`Transformation started for ${config.audience}. ${config.selected.length} outputs queued.`);setTimeout(()=>{setPage('outputs');setToast('');},900)};return <div className="app"><aside className="sidebar"><Logo/><div className="nav-label">CONTROL CENTER</div><nav>{nav.map(([id,icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><i>{icon}</i><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div className="secure-card"><span>◉</span><div><b>Secure Workspace</b><small>RBAC · Encryption · Audit</small></div></div><div className="profile"><div className="avatar">MY</div><div><b>Operator</b><small>Admin</small></div><span>⋮</span></div></div></aside><main className="main">{page==='workspace'&&<Workspace onTransform={transform}/>} {page==='understanding'&&<Understanding/>} {page==='outputs'&&<Outputs/>} {page==='verification'&&<Verification/>} {page==='audit'&&<Audit/>}</main>{toast&&<div className="toast">✓ {toast}</div>}</div>}

export default App;
